#!/bin/bash

RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[1;32m'
NC='\033[0m' # No Color

BASE_REPO="git@github.com:feedhenry-staff"

WFM_CLI_DIR=$(dirname $(readlink -f $0))
WFM_DIR="$WFM_CLI_DIR/.."

APPS="wfm-cloud wfm-auth wfm-mobile wfm-portal"

APPS_DIR="$WFM_DIR"
MODULES_DIR="$WFM_DIR/modules"

# symlink all wfm modules:
#

pullApps () {
  for D in $APPS; do
    cd "$APPS_DIR/$D"
    echo #########
    echo `pwd`
    git pull
  done
}

pullModules () {
  ls "$MODULES_DIR/"
  for D in $MODULES_DIR/*; do
    cd $D
    echo -e "${YELLOW}#########${NC}"
    echo -e "${RED}Pulling:${NC} $D"
    git pull
  done
}

linkApps () {
  for D in $APPS; do
    cd "$APPS_DIR/$D"
    echo -e "${YELLOW}#########${NC}"
    echo -e "${RED}Linking:${NC} $D"
    linkToModules
  done
}

linkToModules () {
  MODULES=$(grep fh-wfm package.json | cut -d':' -f1 | tr -d ' "' | sed 's/fh-//')
  for M in $MODULES; do
    npm link ../modules/$M
  done
}

cleanApps () {
  for D in $APPS; do
    cd "$APPS_DIR/$D"
    echo -e "${YELLOW}#########${NC}"
    echo -e "${RED}Cleaning:${NC} $D"
    rm -rf node_modules
  done
}

cloneApps () {
  for D in $APPS; do
    cd "$APPS_DIR/"
    echo -e "${YELLOW}#########${NC}"
    echo -e "${RED}Cloning:${NC} $D"
    git clone "$BASE_REPO/${D}.git"
  done
}

statusApps() {
  for D in $APPS; do
    cd "$APPS_DIR/$D"
    echo -e "${YELLOW}#########${NC}"
    echo -e "${GREEN}Status: $D"
    echo -e "${NC}"
    git status
  done
}

case $1 in
  pull)
  pullApps
  pullModules
  ;;
  link)
  linkApps
  ;;
  clean)
  cleanApps
  ;;
  clone)
  cloneApps
  ;;
  status)
  statusApps
  ;;
  *)
  echo "Usage: wfm {pull|link|clean|clone}"
esac
