#!/bin/bash

RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[1;32m'
NC='\033[0m' # No Color

BASE_REPO="git@github.com:feedhenry-staff"

WFM_CLI_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WFM_DIR="$WFM_CLI_DIR/.."

MONGO_DIR="$WFM_DIR/mongo"
MONGO_DATA="$MONGO_DIR/data"
MONGO_LOG="$MONGO_DIR/mongodb.log"
MONGO_PID="$MONGO_DIR/mongodb.pid"

APPS="wfm-cloud wfm-auth wfm-mobile wfm-portal"
MODULES="wfm-appform wfm-component-signature wfm-mediator wfm-risk-assessment wfm-sync wfm-template-build wfm-user wfm-vehicle-inspection wfm-workflow wfm-workorder wfm-result"

REPO_DIRS=$APPS
cd $WFM_DIR
for D in modules/*; do
  REPO_DIRS="$REPO_DIRS $D"
done

MODULES_DIR="$WFM_DIR/modules"

echoHeader () {
  echo
  echo -e "${YELLOW}################################################################################${NC}"
  echo -e "${GREEN}${@}${NC}"
  echo -e "${YELLOW}################################################################################${NC}"
}

confirm () {
    # call with a prompt string or use a default
    read -r -p "${1:-Are you sure? [y/N]} " response
    case $response in
      [yY][eE][sS]|[yY])
        true
        ;;
      *)
        false
        ;;
    esac
}

requoteArgs () {
  local res=""
  for x in "${@}" ; do
      # try to figure out if quoting was required for the $x:
      grep -q "[[:space:]]" <<< "$x" && res="${res} '${x}'" || res="${res} ${x}"
  done
  # remove first space and print:
  sed -e 's/^ //' <<< "${res}"
}

pull () {
  for D in $REPO_DIRS; do
    cd "$WFM_DIR/$D"
    echoHeader "Pulling: $D"
    git pull
  done
}

linkApps () {
  for D in $APPS; do
    cd "$WFM_DIR/$D"
    echoHeader "Linking: $D"
    linkToModules
  done
}

linkToModules () {
  MODULES=$(grep fh-wfm package.json | cut -d':' -f1 | tr -d ' "' | sed 's/fh-//')
  for M in $MODULES; do
    npm link ../modules/$M
  done
}

cleanApps () {
  for D in $APPS; do
    cd "$WFM_DIR/$D"
    echoHeader "Cleaning: $D"
    rm -rf node_modules
  done
}

install () {
  for D in $REPO_DIRS; do
    cd "$WFM_DIR/$D"
    echoHeader "Installing: $D"
    npm install
  done
}

cloneApps () {
  cd "$WFM_DIR"
  for D in $APPS; do
    echoHeader "Cloning: $D"
    git clone "$BASE_REPO/${D}.git"
  done
}

cloneModules () {
  if [ ! -d $MODULES_DIR ]; then
    mkdir $MODULES_DIR
  fi
  cd "$MODULES_DIR"
  for D in $MODULES; do
    echoHeader "Cloning: $D"
    git clone "$BASE_REPO/${D}.git"
  done
}

status() {
  for D in $REPO_DIRS; do
    cd "$WFM_DIR/$D"
    STATUS="$(git status -s)"
    AHEAD_BEHIND="$(git status -s -b | grep -E 'ahead|behind')"
    if [ -n "$STATUS" ] || [ -n "$AHEAD_BEHIND" ]; then
      STATUS="$(git -c color.status=always status -s -b)"
      echoHeader "Status: $D"
      echo "$STATUS"
    fi
  done
}

diff () {
  shift
  for D in $REPO_DIRS; do
    cd "$WFM_DIR/$D"
    DIFF="$(git diff --color $@)"
    if [ -n "$DIFF" ]; then
      echoHeader "Diff: $D\n$ git diff --color $@"
      echo "$DIFF"
    fi
  done
}

mongo () {
  if [ ! -d $MONGO_DIR ]; then
    mkdir $MONGO_DIR
  fi
  if [ ! -d "$MONGO_DATA" ]; then
    mkdir $MONGO_DATA
  fi
  PID=`ps x | grep -v grep | grep "mongod" | grep $MONGO_DATA |awk '{ print $1 }'`
  case $1 in
    start)
    if [ ! -z $PID ]; then
      echo "Mongo is already running. pid: $PID"
    else
      mongod --dbpath $MONGO_DATA --logpath ${MONGO_LOG} --fork --logappend
    fi
    ;;
    stop)
    if [ -z $PID ]; then
      echo "Mongo is already stopped."
    else
      echo "Mongo stopping. pid: $PID"
      kill $PID
    fi
    ;;
    status)
    if [ ! -z $PID ]; then
      echo "Mongo is running. pid: $PID"
    else
      echo "Mongo is not running."
    fi
    ;;
    *)
    echo "Usage: wfm mongo {start|stop|status}"
  esac
  #
}

start () {
  cd $WFM_CLI_DIR
  WFM_PATH=$WFM_DIR tmuxinator wfm
}

ackWfm () {
  cd $WFM_DIR
  shift
  ack-grep "$@" REPO_DIRS
}

commit () {
  ARGS=$(requoteArgs "${@}")
  for D in $REPO_DIRS; do
    cd "$WFM_DIR/$D"
    STATUS="$(git status -s)"
    if [ -n "$STATUS" ]; then
      echoHeader "Commit: $D\n$ git $ARGS"
      git status
      confirm && bash -c "git ${ARGS}"
    fi
  done
}

gitWfm () {
  cd $WFM_DIR
  shift
  for D in $REPO_DIRS; do
    echoHeader "Git: $D\n$ git $@"
    cd "$WFM_DIR/$D"
    git "$@"
  done
}

atomWfm() {
  cd $WFM_DIR
  atom wfm-* modules/*
}

case $1 in
  pull)
  pull
  ;;
  link)
  linkApps
  ;;
  clean)
  cleanApps
  ;;
  install)
  install
  ;;
  clone)
  cloneApps
  cloneModules
  ;;
  status)
  status | less -r
  ;;
  diff)
  diff "$@" | less -r
  ;;
  path)
  echo "Script PATH is:"
  echo $WFM_CLI_DIR
  echo $REPO_DIRS
  ;;
  mongo)
  mongo $2
  ;;
  start)
  start
  ;;
  grep)
  ackWfm "$@"
  ;;
  ack)
  ackWfm "$@"
  ;;
  commit)
  commit "$@"
  ;;
  git)
  gitWfm "$@"
  ;;
  atom)
  atomWfm
  ;;
  *)
  echo "Usage: wfm {clone|status|diff|pull|clean|install|link|path|start|mongo|ack}"
esac
